import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import Feed from "@/components/Feed";

const Home = () => {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />
      </main>
    </>
  );
};
export default Home;
